### PR TITLE
Fix paths with special characters

### PR DESCRIPTION
**Pull request by LazaroOnline**
Fixes this issue:
https://github.com/MaloPolese/copy-json-path/issues/5

### CODE REVIEW

**Comment by MaloPolese** [comment]
Hey, thanks a lot for your contribution 💙.

Good job on finding that bug!

---
Because `is-var-name` does not include typing the typescript build fails

I think you can fix this bug without using an external dependency.

First of all, if you use `JSON.stringify(val)` you can freeze the value which avoids doing a replacement.
Secondly, you can do something like this to find out when there is a unique character.

```ts
const prohibitedChar = ['.', '\\"', '\\'];
let hasSpecialChar = prohibitedChar.some((v) => JSON.stringify(segment).includes(v));
```

**Comment by LazaroOnline** [comment]
You were right, "is-var-name" is not needed, here is an update to the PullRequest that handles the issue correctly with unit-tests.
I wasn't able to do an end to end test installing the extension though, only the unit tests.

I hope the pull request helps so the issue can be fixed.

**Comment by LazaroOnline** [comment]
There are too many prohibited chars to make a list of them.
It is safer to do a white list than a black list.
For a whitelist it is easier to user RegExp so we can define ranges like A-Z.
I added some common diacritic characters with this other ranges: 
À-Ö
Ø-ö
ø-ÿ
That was taken from [this StackOverflow answer here](https://stackoverflow.com/questions/20690499/concrete-javascript-regular-expression-for-accented-characters-diacritics/26900132#26900132).

The unit-tests ensures these ranges works with a list of valid and invalid characters.

In the future we could add more unicode alphabets to the white-list of characters that doesn't require escaping, since it is more convenient and easier to read than the quoted version.

**Comment by LazaroOnline** [comment]
To allow other language character-sets without double quotes, there is an StackOverflow regarding that [here](https://stackoverflow.com/questions/15861088/regex-to-match-only-language-chars-all-language) .
that suggest using [xRegExp ](https://xregexp.com/plugins/) library, or the [Unicode reference](http://unicode.org/charts/index.html) to get the char ranges, for example Cyrillic would be `'\u0400-\u04FF'`, we just need to make sure to unit-test all values within the range to prevent an invalid character from making it into the white-list.

**Comment by MaloPolese** [comment]
LGTM, I merge it. 🎉

Thank you for your contribution! 😀

**Pull request merged**
